### ISSUE TITLE
Specs not working for graded code block

### ISSUE THREAD

**Issue by bpurinton** [DPI-WE/our-own-classes-level-up#1]
@heratyian 

A student reported an error with the tests, and I confirmed it. Here is my answer for the graded code block:

```ruby
class Car
  attr_reader :make, :model, :year

  def initialize(make, model, year)
    @make = make
    @model = model
    @year = year
  end

  # TODO: Custom setters for make, model, and year
  def make=(value)
    unless value.is_a?(String)
      raise TypeError, 'Make must be a string'
    end

    @make = value
  end
	
  def model=(value)
    unless value.is_a?(String)
      raise TypeError, 'Model must be a string'
    end

    @model = value
  end
	
  def year=(value)
    unless value.is_a?(Integer)
      raise TypeError, 'Year must be an integer'
    end

    @year = value
  end
	
end

# Test your Car class
car = Car.new("toyota", "camry", 2021)
pp car.make
pp car.model
pp car.year

# Change and then print the make
car.make = "ford"
pp car.make

# Change and then print the model
car.model = "explorer"
pp car.model

# Change and then print the year
car.year = 2022
pp car.year
```

That works, but when I run the test below it, I get the following error:

--- 

![image](https://github.com/DPI-WE/our-own-classes-level-up/assets/12408296/6442771c-a798-4b77-bb55-08bcd4d53ebc)

---

I would suggest refactoring the spec into several different specs, as I did in the [User Class code block in the previous Classes lesson](https://learn.firstdraft.com/lessons/78-ruby-intro-our-own-classes#inheritance:~:text=joe%40example.com%22-,User%20class,-1). Here is the source code for that graded code block, where I have broken each thing being tested into a separate test, and provided a single `expect` in each case: 

https://github.com/appdev-lessons/ruby-intro-our-own-classes/blob/main/content.md?plain=1#L325-L368

This is painstaking, but it is our best practice for writing specs in the intro to Ruby. I.e., we want each individual requirement to be separately runnable, with points achievable on each part of the test.

In your example, each test should have a `title` like "Car class allows changing the make and stores it in uppercase", "Car class allows changing the make and stores it in uppercase", etc.

See the [how to guide](https://learn.firstdraft.com/lessons/3-how-to-write-a-lesson#graded-ruby-repl--repl-test)

## EDIT / UPDATE

Okay, I see that there is actually just a syntax error in the spec (fixing this does make the specs pass), so you don't need to rewrite anything and just fix the missing quote / `do`:

https://github.com/DPI-WE/our-own-classes-level-up/blob/main/content.md?plain=1#L147

However, optionally, you can break apart the test to conform to our style in previous lessons (not super necessary though)

**Comment by bpurinton** [comment]
I fixed the problem on this commit: https://github.com/appdev-lessons/our-own-classes-level-up/commit/dda7a596b4a19f4fddaeed88509d2882ca238831

But I leave the issue open in case you want to update / break up the tests. Feel free to close this issue!

**Comment by heratyian** [comment]
Thank you Ben! I made a last minute decision to add the `year` test and then pushed. My bad. I will refactor the tests into separate blocks so they can run separately.

**Comment by heratyian** [comment]
Updated here 0611ea6

Thank you again for the hotfix @bpurinton !
