### ISSUE TITLE
Re-run test button crashes

### ISSUE THREAD

**Issue by heratyian** [DPI-WE/our-own-classes-level-up#3]
I broke up the car class tests into separate blocks, but I'm crashing the app when I click "Re-run tests". Is this an issue with my tests?

<img width="140" alt="image" src="https://github.com/DPI-WE/our-own-classes-level-up/assets/10753327/180e1047-370d-40bf-8e55-735148c06665">

<img width="876" alt="image" src="https://github.com/DPI-WE/our-own-classes-level-up/assets/10753327/b5e8a816-6158-420d-82b0-40129ed8dfb9">

**Comment by heratyian** [comment]
cc: @bpurinton

**Comment by heratyian** [comment]
related context. I only have 5 tests but it's counting 6 points 
<img width="622" alt="image" src="https://github.com/DPI-WE/our-own-classes-level-up/assets/10753327/ed06a482-f52c-417e-b47c-73a95a038bb4">

I can only get 5 points until I click "re-run tests", which crashes but then gives me the full 6 points. Am I configuring this wrong?

**Comment by bpurinton** [comment]
Hmm. I don't have time to look into this now. Maybe you can revert to the quick fix / combined tests? Hopefully time soon to figure out what's going wrong here. Maybe you can put the crashing version on a new branch here and we can use that to debug when we have time to circle back. I can make a new issue and link such a branch.

**Comment by heratyian** [comment]
I think there might be a caching issue on the learn side. I combined the tests together into 1 describe block and it incremented the total points.
<img width="640" alt="image" src="https://github.com/DPI-WE/our-own-classes-level-up/assets/10753327/e06afc7e-406b-4518-9ab5-7dbe813db44f">

**Comment by heratyian** [comment]
I just merged in a fix that just changes the id of the repl from "#car_class" to "#car_class_quiz" and it fixes the issue. Seems like a Learn bug.  Is there a good place to log this issue? @bpurinton

**Comment by bpurinton** [comment]
That is unexpected! So just to be sure I understand, this commit completely resolved the issue: https://github.com/DPI-WE/our-own-classes-level-up/pull/6/commits/c77cb50badad87758d210239c714837405a31f6a?

If so I'll log the issue and point out that commit.

**Comment by heratyian** [comment]
Correct
